IV_LENGTH = 16
KEY_LENGTH = 32
RSA_KEY_LENGTH = 2048
RSA_PUBLIC_EXPONENT = 65537
BLOCK_SIZE = 128
MESSAGE = b"a secret message"
ENC_EXT = ".enc"
JSON_EXT = ".json"
RSA_PUBLIC_KEYPATH = r"C:\Users\thuyen23\Desktop\RSATest\public_key.pem"
RSA_PRIVATE_KEYPATH = r"C:\Users\thuyen23\Desktop\RSATest\private_key.pem"
IMG_PATH = r"C:\Users\thuyen23\Desktop\RSATest\sig1.png"
DECR_IMG_PATH = r"C:\Users\thuyen23\Desktop\RSATest\sig1test.png"
