IV_LENGTH = 16
KEY_LENGTH = 32
RSA_KEY_LENGTH = 2048
RSA_PUBLIC_EXPONENT = 65537
BLOCK_SIZE = 128
MESSAGE = b"a secret message"
ENC_EXT = ".enc"
JSON_EXT = ".json"
RSA_PUBLIC_KEYPATH = r"%PATH%public_key.pem"
RSA_PRIVATE_KEYPATH = r"%PATH%private_key.pem"
IMG_PATH = r"%PATH%sig1.png"
DECR_IMG_PATH = r"%PATH%sig1test.png"
